// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlataformaRedencao.Infra.Data.Context;

#nullable disable

namespace PlataformaRedencao.Infra.Data.Migrations
{
    [DbContext(typeof(PlataformaRedencaoDbContext))]
    partial class PlataformaRedencaoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlataformaRedencao.Domain.Entities.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Atual")
                        .HasColumnType("boolean")
                        .HasColumnName("atual");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("complemento");

                    b.Property<int>("EntidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("entidade_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pais");

                    b.Property<int>("TipoEntidade")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_entidade");

                    b.Property<DateTime?>("VigenteAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigente_ate");

                    b.Property<DateTime?>("VigenteDesde")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigente_desde");

                    b.HasKey("Id");

                    b.HasIndex("Atual");

                    b.HasIndex("EntidadeId", "TipoEntidade");

                    b.ToTable("endereco", "membros");
                });

            modelBuilder.Entity("PlataformaRedencao.Domain.Entities.Igreja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTime?>("AtualizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizada_em");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<DateTime>("DataFundacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fundacao");

                    b.Property<string>("Denominacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("denominacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<int?>("EnderecoId")
                        .HasColumnType("integer")
                        .HasColumnName("endereco_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("PastorResponsavel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pastor_responsavel");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("site");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.ToTable("igreja", "membros");
                });

            modelBuilder.Entity("PlataformaRedencao.Domain.Entities.Membro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<DateOnly>("DataAdmissao")
                        .HasColumnType("date")
                        .HasColumnName("data_admissao");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("integer")
                        .HasColumnName("endereco_id");

                    b.Property<int>("Escolaridade")
                        .HasColumnType("integer")
                        .HasColumnName("escolaridade");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("integer")
                        .HasColumnName("estado_civil");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("integer")
                        .HasColumnName("igreja_id");

                    b.Property<int>("ProfissaoId")
                        .HasColumnType("integer")
                        .HasColumnName("profissao_id");

                    b.Property<char>("Sexo")
                        .HasColumnType("character(1)")
                        .HasColumnName("sexo");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.Property<int>("TipoAdmissao")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_admissao");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.HasIndex("IgrejaId");

                    b.HasIndex("ProfissaoId");

                    b.ToTable("membro", "membros");
                });

            modelBuilder.Entity("PlataformaRedencao.Domain.Entities.Profissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("profissao", "membros");
                });

            modelBuilder.Entity("PlataformaRedencao.Domain.Entities.Igreja", b =>
                {
                    b.HasOne("PlataformaRedencao.Domain.Entities.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("PlataformaRedencao.Domain.Entities.Membro", b =>
                {
                    b.HasOne("PlataformaRedencao.Domain.Entities.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaRedencao.Domain.Entities.Igreja", "Igreja")
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaRedencao.Domain.Entities.Profissao", "Profissao")
                        .WithMany()
                        .HasForeignKey("ProfissaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Contato", "Contato", b1 =>
                        {
                            b1.Property<int>("MembroId")
                                .HasColumnType("integer");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("email");

                            b1.Property<string>("Telefone")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("telefone");

                            b1.HasKey("MembroId");

                            b1.ToTable("membro", "membros");

                            b1.WithOwner()
                                .HasForeignKey("MembroId");
                        });

                    b.OwnsOne("PlataformaRedencao.Domain.ValueObjects.NomePessoa", "NomePessoa", b1 =>
                        {
                            b1.Property<int>("MembroId")
                                .HasColumnType("integer");

                            b1.Property<string>("PrimeiroNome")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("primeiro_nome");

                            b1.Property<string>("SobreNome")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("sobrenome");

                            b1.HasKey("MembroId");

                            b1.ToTable("membro", "membros");

                            b1.WithOwner()
                                .HasForeignKey("MembroId");
                        });

                    b.Navigation("Contato")
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Igreja");

                    b.Navigation("NomePessoa")
                        .IsRequired();

                    b.Navigation("Profissao");
                });
#pragma warning restore 612, 618
        }
    }
}
